### ISSUE TITLE
Add some colour to about page!

### ISSUE THREAD

**Issue by pratik-IDWT** [In-Data-We-Trust/In-Data-We-Trust.github.io#111]
The existing about page feels a bit same same with a block of text. 

Need to update it based on feedback from Michelle!

![Image](https://user-images.githubusercontent.com/112123058/219486422-8fd4dd00-7cba-4ade-aae8-4f8d4e12ea55.png)

**Comment by nelsonic** [comment]
_Really_ love the simplicity of your site! 😍
