### ISSUE TITLE
Update Original Article with Feedback from Nelson

### ISSUE THREAD

**Issue by pratik-IDWT** [In-Data-We-Trust/In-Data-We-Trust.github.io#23]
- [x] Migrate original article from Medium to my website
- [x] Update the page with the information here https://github.com/dwyl/technology-stack/issues/98
- [x] Choose cool image to use as opening image

The post on my website is here - https://github.com/In-Data-We-Trust/In-Data-We-Trust.github.io/blob/main/_posts/2022-09-01-Data-Stacks-and-are-we-forgetting-the-main-purpose-of-them.markdown

**Comment by pratik-IDWT** [comment]
Original Article from Medium has now been migrated to my own Website!! 

## On Medium

<img width="620" alt="image" src="https://user-images.githubusercontent.com/112123058/189751747-ce762248-acd7-4b90-8167-c063e1042d9f.png">


## On my own website

<img width="770" alt="image" src="https://user-images.githubusercontent.com/112123058/189752034-98ff0006-b3d2-4944-bbd1-74d0dda30844.png">


I noticed at the end of the page is a share too option. I should probably replace **Facebook** with **LinkedIn** to be more relevant

<img width="408" alt="image" src="https://user-images.githubusercontent.com/112123058/189752188-90607dd0-d03a-4dc1-8acf-7b233ba2b2ac.png">

**Comment by pratik-IDWT** [comment]
# Updating the Article

I have read the comments on https://github.com/dwyl/technology-stack/issues/98 and also re-read the article. It is missing a _**Wow**_ factor to get me to keep reading. Even though I wrote it a month ago, It does need to be jazzed up. 

I will review it with the feedback from Nelson and update

**Comment by nelsonic** [comment]
Happy to help if you host your blog somewhere I can submit a PR. 😜

**Comment by pratik-IDWT** [comment]
The blog post is hosted here - https://github.com/In-Data-We-Trust/In-Data-We-Trust.github.io/blob/main/_posts/2022-09-01-Data-Stacks-and-are-we-forgetting-the-main-purpose-of-them.markdown

The world of public repo's is a bit new to me. What is the easiest way? 

- Do I need to get a seat on Github and add you to the project? or
- Or is that not needed as it's public

Happy either way, The cost is less than a price of a pint of beer and the seat for you would be the price of a half pint in London each month

**Comment by nelsonic** [comment]
If it’s public you don’t need to pay. 😉

**Comment by pratik-IDWT** [comment]
## Brief Update to this ticket

After writing the about us page on the website, I will re-position this article to

> Data Stacks - Why They Can Kill Your Startup

## Opening Sentence

Remove this:
![image](https://user-images.githubusercontent.com/112123058/190875170-7aaa7a7b-f70a-42db-b43c-015d00bc4865.png)

## Structure and re-write

I need to re-write it and review it harshly in paint with red-line. Aiming to get this done by EOD Monday and updated. Will post my updates on here in paint shortly.

**Comment by pratik-IDWT** [comment]
## Re-write of opening paragraph. 

I have reviewed the opening graphs and they need a big upheaval. 

![image](https://user-images.githubusercontent.com/112123058/191000296-a12242b4-b62d-489c-9e22-942a7105fcad.png)

This article should emphasise, issues, signs of them, and what I suggest. 

Then I will make a 2nd post for Azure stack I've built and a 3rd post for an AWS stack I've built.

**Comment by pratik-IDWT** [comment]
## Brief Update

Merged my changes to master. Will review on Paint with a harsh **so what** and **what's in it for me attitude**

MR: #43

**Comment by pratik-IDWT** [comment]
Made more changes and merged to the live website. #44 

Will review tomorrow with a fresh pair of Eyes.

**Comment by pratik-IDWT** [comment]
Few more updates to make:

Change Below "_Needed_" to "_required_" 

![Image](https://user-images.githubusercontent.com/112123058/191113142-a0b3d9c7-3f5a-4365-a9f3-c0e8b6ca8d4f.png)


Update to Solution 1 section:


![Image](https://user-images.githubusercontent.com/112123058/191113581-754d4e8c-09ad-4f25-bb21-0bb6e3187436.png)


Update to solution 2 section:



![Image](https://user-images.githubusercontent.com/112123058/191113820-d9fe7bce-bbb2-415d-bb24-d8ee6b025d40.png)

**Comment by pratik-IDWT** [comment]
https://github.com/In-Data-We-Trust/In-Data-We-Trust.github.io/pull/51

Both Articles are updated. Will be receiving some further feedback but for now, time to close this chapter and move onto the next ones!
