### ISSUE TITLE
Update About PAge with company information

### ISSUE THREAD

**Issue by pratik-IDWT** [In-Data-We-Trust/In-Data-We-Trust.github.io#31]
## Overview

The company website needs to provide information about:

- In Data We Trust
- Me (Pratik Patel) and 
- Blog Posts / Thought leadership / PR

As part of this ticket, I will update the **About us** page:
- Public Link on internet - https://www.indatawetrust.co.uk/about/
- Location of markdown file in repository - https://github.com/In-Data-We-Trust/In-Data-We-Trust.github.io/blob/main/_pages/about.md

### Why we were founded
Why did I found the company? 

Simplicity beats complexity. 

Time to engineer, analyse and provide an answer is the most important item for a start up or growing business.

If this time is too long, then you won't be a data driven business but a business running on opinions. 

We want to help organisations use the right tools and processes to utilise data to make an impact.

Enabling analysts and scientists to engineer their own data with a simple stack, is infinitely better than a complicated solution that drives a greater distance between both sides. Especially when the business is finding it's market-fit and attracting customers.

The tools we have let's curious analysts and scientists begin to engineer their own data so they understand the end-to-end process. Removing the data engineering bottleneck and driving insight!

### What we have seen
Firsthand - a cutting edge data engineering stack, only delays the time to obtain an answer and make data available. This is very ironic. Suited to FTSE 100 companies. NOT suited to SME's

### What we want to improve

Bring the simple back in data and bring the trust back in data. 

### How we work? 

Suggesting and working with tools used first hand that do what is needed and are simple. The simple doesn't mean it isn't fit for purpose, quite the opposite. It is just right for what an organisation needs. 

We have an Azure recommend stack and an AWS recommend stack. Please feel free to enquire to learn more about it.

(Our links to our GitHub repos for them are here)

We've kept it open source so you can see what we suggest. We can guide you on how to implement and utilise them.

### What Else?

Leverage Nelson comments to include on here too

**Comment by pratik-IDWT** [comment]
# What is the purpose of this page?

I'm a prospective customer, I've already landed on the website and want to quickly know if this company is right for me.

So it needs to:
- provide an overview of the company
- not be too long
- have a HOOK to us solving your problems

I have an hour or 2 this afternoon waiting in a coffee shop before meeting some friends.

I'll draft up something. Remembering **less is more!**

**Comment by pratik-IDWT** [comment]
# More ideas when waiting for my physio

- Company principles (simplicity, two other catchy ones to be considered)

**Comment by nelsonic** [comment]
@pratik-IDWT hope your physio goes well. 🤞 

Totally agree with the Less-is-More mindset. ❤️ 
But you can pre-qualify leads  by having _enough_ info on the page ℹ️ 
to answer the questions people are _thinking_ when they are viewing your site. ❓ 

Happy to review and provide feedback if you need. 💬

**Comment by pratik-IDWT** [comment]
Thanks @nelsonic for the comment. 

My Physio went well, I got dischared and told to exercise myself now. He told me to stop the running and focus on strength to make sure my knee works into my older years so I will follow that advise. 

I've pushed a PR to the live site about page. I will review on Friday/Saturday and update. 

It isn't the finished article as it reads like one big word article. I need some pictures and tables to break it up! I think someone has said that before to me 😝 

Appreciate some feedback. I think I will lift a few items from the first blog post and place into here to provide the hook to read more. 

Time for me to head out and catch up with some friends over 🍛  and 🍺 . 

I've got a bug on a photo I need to work out and Also an emoji that isn't appearing 🤷‍♂️ 

Link to Website - https://www.indatawetrust.co.uk/about/
Link to markdown file - https://github.com/In-Data-We-Trust/In-Data-We-Trust.github.io/blob/main/_pages/about.md

**Comment by pratik-IDWT** [comment]
Final point before I hit **shutdown**

To focus on the **What do we believe in section?**

It's too long. If it wasn't my site, I might close it down altogether. 

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/112123058/190453459-3ba13a15-7513-4e17-a3ba-4dcbfd697b21.png">

**Comment by pratik-IDWT** [comment]
# Writing up my feedback before I open up VSCode

My mind is better at reviewing text rendered on the website. So will document the changes first, prior to opening up VScode.

## About 

<img width="718" alt="image" src="https://user-images.githubusercontent.com/112123058/190639577-d63601b6-67fd-4591-af7c-d44c2ad6df1a.png">

I use the word _**founded**_ in here and then later on. 

Will re-phrase to

`Hey! In Data We Trust uses simple data solutions to enable organisations to grow. We love working with data because we've seen first hand how it can transform organisations.` 

## Why we were Founded?

First feedback from the wife - change title sentence 

<img width="304" alt="image" src="https://user-images.githubusercontent.com/112123058/190640223-c397233d-138f-47f4-abf9-91e7e7e96b70.png">

Rephase to:

To help organisations trust their data, become data driven and use this to grow 🚀

Data stacks and solutions can easily become complicated and time consuming to build new data feeds. We guard against this pitfall by have a principle of doing the exact opposite.

> Simplicity beats complexity.

## What do we Believe in?

Maybe re-name the title to, "What does your data stack need to do" - _Needs more fine-tuning_

Updated in paint - this was better than reviewing in VScode for my brain

![image](https://user-images.githubusercontent.com/112123058/190642864-068b5f6a-1cd1-4dff-9510-fb5a141b9ca3.png)

## How Can We Help You?

![image](https://user-images.githubusercontent.com/112123058/190643614-46a13048-3e82-490a-a310-e8145304c49d.png)

### Start up section

![image](https://user-images.githubusercontent.com/112123058/190644079-c090c9b9-8907-42c2-a29e-8c4dc3c62869.png)

## We already have a data-stack

![image](https://user-images.githubusercontent.com/112123058/190644329-dfaf625c-b267-49fb-9359-df3087a34dee.png)

## What have we Learnt

![image](https://user-images.githubusercontent.com/112123058/190644880-d6216ff1-2a73-4e4f-bbbd-bea1d7831b05.png)

## Enquire

![image](https://user-images.githubusercontent.com/112123058/190645218-4085c0c1-1d70-4f28-9c52-745ffbc3fe63.png)

**Comment by pratik-IDWT** [comment]
@nelsonic  - Please can you review the https://www.indatawetrust.co.uk/about/ page :) 

I've done all my updates. It's better than my first post, so I will look at that next to see how I take my new found _slight improved_ writing skills


Link to markdown in master if you want it there - https://github.com/In-Data-We-Trust/In-Data-We-Trust.github.io/blob/main/_pages/about.md

**Comment by pratik-IDWT** [comment]
## Few More updates Suggested by my Friend Rajiv

<img width="463" alt="image" src="https://user-images.githubusercontent.com/112123058/190682322-b93b9de2-2aaa-42a0-a46b-098843a1dfe2.png">

**Comment by pratik-IDWT** [comment]
Page has been updated with comments from Rajiv. 

I removed the _**What have we learnt**_ section - and moved parts of it into Contact us. Was adding minimal value it being there. 

<img width="793" alt="image" src="https://user-images.githubusercontent.com/112123058/190687988-e33849d4-5843-43df-954f-6f8049573799.png">

**Comment by pratik-IDWT** [comment]
## More feedback

Need to find some photo's, feedback from another friend:

> I like the wording you used, just need some pics to make it pop

### Opening paragraph 

Use this as an option after opening paragraph

https://pixabay.com/vectors/statistic-analytic-diagram-1564428/

<img width="205" alt="image" src="https://user-images.githubusercontent.com/112123058/190859347-7c83ddb5-d68a-4b3d-9c86-68b25ef4b38e.png">


### Simplicity 

Underneath the simplicity quote. One more photo outlining the all the icons in a stack with 20 tools Vs 3. 

I can likely pull this together.

However, I will use the below for now:

https://www.istockphoto.com/vector/different-plan-concept-gm1347175709-424727470#

<img width="482" alt="image" src="https://user-images.githubusercontent.com/112123058/190871885-9710d313-aa09-4cff-b62e-962149bc271e.png">

## Conclusion 

Then that's it for an MVP!

I need to consider the deadline for this if EOD Wednesday 21st September, because I'm going to a networking event on Thursday.

Will make the brief changes above and then move onto the first original article.

**Comment by pratik-IDWT** [comment]
Note to self, to stop manually adding and removing PR's to Git issues - This keeps bugging and removing one's that were already linked 🤦🏽‍♂️

**Comment by pratik-IDWT** [comment]
I've finished my final updates for now to this ticket. I will move to closed. 

@nelsonic , let me know your thoughts and I can update after. Time to now move onto #23
